### ISSUE TITLE
Set terraform output variables as multi-job output pipeline variables

### ISSUE THREAD

**Issue by charleszipp** [charleszipp/azure-pipelines-tasks-terraform#137]
Set the pipeline variables generated from terraform output to be accessible across multiple jobs within a stage as documented [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-a-multi-job-output-variable).

This would require setting the `isOutput=true` flag when setting the variable.

Currently the [azure-pipelines-task-lib](https://github.com/microsoft/azure-pipelines-task-lib/tree/master/node) does not provide a means to do this. See [this issue](https://github.com/microsoft/azure-pipelines-task-lib/issues/640). However, if can write the `task.setvariable` command manually to stdout then this should still be possible.

**Comment by FernandoMiguel** [comment]
I'm guessing this is why I'm seeing this?
```yaml
Evaluating: and(succeeded(), eq(variables['TERRAFORM_PLAN_HAS_CHANGES'], 'true'))
Expanded: and(True, eq(Null, 'true'))
Result: False
```
