### ISSUE TITLE
It seems that after latest update extension stopped working properly

### ISSUE THREAD

**Issue by rhollins** [charleszipp/azure-pipelines-tasks-terraform#139]
I just noticed that from this morning I'm getting following init error on every terraform run even if its different subscription and backed storage account.

Wonder if it is not connected to yesterday update 0.5.10 (Latest)

Initializing the backend...

Error configuring the backend "azurerm": 4 errors occurred:
	* : invalid or unknown key: client_id
	* : invalid or unknown key: client_secret
	* : invalid or unknown key: subscription_id
	* : invalid or unknown key: tenant_id

##[error]Terraform command 'init' failed with exit code '1'.

I'm using the extension from yaml pipeline:

```
 - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
    displayName: "Terraform Init - ${{ parameters.ENV }}"
    inputs:
      command: init
      backendType: azurerm
      workingDirectory: '${{ parameters.WORK_DIR }}'
      backendServiceArm: ${{ parameters.STATE_SC }}
      backendAzureRmResourceGroupName: ${{ parameters.STATE_SA_RG_NAME }}
      backendAzureRmStorageAccountName: ${{ parameters.STATE_SA_NAME }}
      backendAzureRmContainerName: ${{ parameters.STATE_CONTAINER_NAME }}
      backendAzureRmKey: ${{ parameters.STATE_BACKEND_KEY }}
```

From log file:

/data/home/<USER>/agent/_work/_tool/terraform/0.11.13/x64/terraform init -backend-config=storage_account_name=<STORAGE_ACC_NAME_HERE> -backend-config=container_name=<CONTAINER_NAME_HERE> -backend-config=key=<STATE_BLOB_HERE> -backend-config=resource_group_name=<RG_NAME_HERE> -backend-config=subscription_id=<SUBSCRIPTION_ID_HERE> -backend-config=tenant_id=*** -backend-config=client_id=*** -backend-config=client_secret=***

I'm using Terraform v0.11.13 and also have this problem on v0.11.14

I've noticed that main difference I that when it was working before the extension was using following parameters:

-backend-config=arm_subscription_id
-backend-config=arm_tenant_id
-backend-config=arm_client_id
-backend-config=arm_client_secret

and now it's skipping the arm part:

-backend-config=subscription_id
-backend-config=tenant_id
-backend-config=client_id
-backend-config=client_secret

Here is the commit that broke it for me; https://github.com/charleszipp/azure-pipelines-tasks-terraform/commit/787880bf2e4150605c94e71e7091e0420da3e9f3#diff-3c7e350e12d6548cac45c54ed9025df1
