### ISSUE TITLE
Issue when using TF state in different azure subscription then the deployed resources after upgrade to 0.12

### ISSUE THREAD

**Issue by rhollins** [charleszipp/azure-pipelines-tasks-terraform#141]
Hello, 

Since terrafrm upgrade to v0.12.25 (and ARM 2.11.0) yaml pipeline which didn't change no longer works. (previous version of terraform was 0.11.4 and arm 1.38.0)

I'm using two service connections one for init to access terraform state storage account and the other to perform plan and this plan is executed in different subscription then were the storage account exists.

The terraform init step works fine but terraform plan gives the following error:

**Error: Error loading state: Error retrieving keys for Storage Account "STORAGE ACCOUNT NAME": storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'RESOURCE GROUP NAME' could not be found."**

I noticed that other pipelines with also new terraform version, where state and deployment are in the same subscription, works fine.

yaml code:

```
  - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
    displayName: 'Install Terraform ${{ parameters.TF_VERSION }}'
    inputs:
      terraformVersion: ${{ parameters.TF_VERSION }}

  - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
    displayName: "Terraform Init - ${{ parameters.ENV }}"
    inputs:
      command: init
      backendType: azurerm
      workingDirectory: '${{ parameters.WORK_DIR }}'
      backendServiceArm: ${{ parameters.STATE_SC }}
      backendAzureRmResourceGroupName: ${{ parameters.STATE_SA_RG_NAME }}
      backendAzureRmStorageAccountName: ${{ parameters.STATE_SA_NAME }}
      backendAzureRmContainerName: ${{ parameters.STATE_CONTAINER_NAME }}
      backendAzureRmKey: ${{ parameters.STATE_BACKEND_KEY }}

  - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
    displayName: "Terraform Plan - ${{ parameters.ENV }}"
    inputs:
      command: plan
      backendType: azurerm
      workingDirectory: '${{ parameters.WORK_DIR }}'
      commandOptions: '-out=tfplan
                      ${{ parameters.COMMAND_PARAMS }}'
      environmentServiceName: ${{ parameters.SC }}
```

**Comment by charleszipp** [comment]
Hey @rhollins I would suggest adding `ensureBackend: true` to your inputs for the `init` step. This will create the resource group if it cannot find it. Even if this isnt the behavior you may want, it may help you to trace down why it cant find the resource group your are targeting. For example, maybe the service principal/connection is associated to the wrong subscription or scoped to narrowly. The `ensureBackend` will create the resource group. If you still cant find it after it creates it, that may point to an issue with the service connection being used.

**Comment by charleszipp** [comment]
retracting earlier statement as i missed the part about the issue being during plan. I think this is likely a defect. Will mark as such and see if we can repro. During the plan stage, terraform still needs credentials to the backend. However, those are typically captured in a state file as part of the init step that is local to the machine running terraform. Could you provide some details about what agents you are using? Are these self-hosted or hosted? Which OS?

**Comment by rhollins** [comment]
We are running this on self-hosted Ubuntu 18.04-LTS all those yaml steps provided are executed as one stage on single agent VM and the plan as output files is being saved as pipeline artifact for the apply stage. I will also have a closer look at the state file on the agent try to see if I can find more details.

**Comment by rhollins** [comment]
Just to give an update I checked on the agent machine that indeed terraform init creates state file with all the details of the storage account and credentials to get there.

```
{
    "version": 3,
    "serial": 1,
    "lineage": "81cb306b-2cf4-7521-83c6-bc143ab6fb9f",
    "backend": {
        "type": "azurerm",
        "config": {
            "access_key": null,
            "arm_client_id": "...",
            "arm_client_secret": "...",
            "arm_subscription_id": "...",
            "arm_tenant_id": "...",
            "client_id": null,
            "client_secret": null,
            "container_name": "...",
            "endpoint": null,
            "environment": null,
            "key": "website-dev.tfstate",
            "msi_endpoint": null,
            "resource_group_name": "...",
            "sas_token": null,
            "storage_account_name": "...",
            "subscription_id": null,
            "tenant_id": null,
            "use_msi": null
        },
        "hash": 1983920158
    },
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {},
            "depends_on": []
        }
    ]
}
```

**Comment by janegilring** [comment]
I also ran into the same issue when having backend state and targets for the configuration in different subscription. For me it worked fine after setting the ARM_ACCESS_KEY as an environment variable in the pipeline.

**Comment by scott-doyland-burrows** [comment]
This works - as long as the service principal has access to all required subs.  Appreciate this isn't the same setup as the OP.

1. azure devops service connection with sub1 defined
2. init/backend uses the service connection and a rg/stg in that sub1 all defined via the extension settings
3. plan uses the service connection BUT has a different sub hardcoded in the .tf file where resources are deployed
4. Also possible to then setup provider aliases all with different subs hardcoded in .tf 

So I have statefile on sub1 and resources getting created on multiple other subs.

**Comment by ausfestivus** [comment]
> For me it worked fine after setting ARM_ACCESS_KEY (with the access key for the backend storage account) as an environment variable in the pipeline.

I encountered this same problem yesterday. The tip above was what solved it for me. Im including my YAML for the tasks to help the next person understand what needs to be done.

```yaml
      - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
        displayName: 'terraform init'
        inputs:
          command: init
          commandOptions: '-no-color -input=false -reconfigure'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Baseline/'
          backendType: azurerm
          backendServiceArm: ${{ variables.azureServiceConnectionNameMaster }}
          backendAzureRmResourceGroupName: '$(tfSharedStateRg)'
          backendAzureRmStorageAccountName: '$(tfSharedStateSa)'
          backendAzureRmContainerName: 'remed'
          backendAzureRmKey: '$(tfSharedStateKey)'

...

      - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
        displayName: 'terraform plan'
        inputs:
          command: plan
          commandOptions: '-no-color -out="./tfplan" -input=false -detailed-exitcode'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Baseline/'
        env:
          ARM_SUBSCRIPTION_ID: '$(TARGET_ARM_SUBSCRIPTION_ID)'
          # we have to set an ENV var for the SP secret depending on which branch we are running in.
          ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/dev') }}:
            ARM_CLIENT_SECRET: '$(CLIENT_SECRET_DEV)'
            ARM_ACCESS_KEY: '$(SA_SECRET_DEV)'
          ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
            ARM_CLIENT_SECRET: '$(CLIENT_SECRET_PROD)'
            ARM_ACCESS_KEY: '$(SA_SECRET_PROD)'
```
