### ISSUE TITLE
terraform init not working with inline backend config storage account

### ISSUE THREAD

**Issue by gabrieljoelc** [charleszipp/azure-pipelines-tasks-terraform#147]
I am using a service principal with a self-configured `terraform init` task. I uploaded a secure `.env` for the service principal as specified in the [Terraform docs](https://www.terraform.io/docs/providers/azurerm/guides/service_principal_client_secret.html#configuring-the-service-principal-in-terraform). I also need to specify a different storage account name and secret and am trying to do this through Command Options with this:
```
-backend-config 'storage_account_name=$(STORAGE_ACCOUNT_NAME)' -backend-config 'access_key=$(STORAGE_ACCOUNT_ACCESS_KEY)'
```
I added the specified variables to Variables and I see this in the logs:
```
2020-07-08T00:06:07.8828468Z [command]/opt/hostedtoolcache/terraform/0.11.14/x64/terraform init -backend-config 'storage_account_name=mystorageaccount' -backend-config 'access_key=***'
```
but the init never finishes and I see this at the bottom of the logs when I cancel the build:
```
2020-07-08T00:06:08.0050476Z [0m[1mInitializing the backend...[0m
2020-07-08T00:06:08.0055396Z [0m[1mstorage_account_name[0m
2020-07-08T00:06:08.0056400Z   The name of the storage account.
2020-07-08T00:06:08.0057501Z 
2020-07-08T00:21:42.4927065Z   [1mEnter a value:[0m [0m
```

Why is it challenging me for the storage account name name even though I passed it in?

**Comment by scott-doyland-burrows** [comment]
Is it anything to do with the syntax of the -backend-config.  I am running terraform 0.13.0 beta and need to use the following (ie remove the ' )

-backend-config storage_account_name=$(STORAGE_ACCOUNT_NAME) -backend-config access_key=$(STORAGE_ACCOUNT_ACCESS_KEY)

By the way, if you use an environment variable of 

TF_CLI_ARGS =  "-no-color"

then it will remove all those odd black questions marks and make it easier to read.

Scott

**Comment by dox1042** [comment]
I work with Gabe let me give that a go and report back.

**Comment by dox1042** [comment]
No Joy
`Time:2020-07-08T15:07:36.0589964Z, RequestInitiated=Wed, 08 Jul 2020 15:07:35 GMT, RequestId=f9ef5c86-701e-0015-4f39-550787000000, API Version=, QueryParameterName=, QueryParameterValue=[0m[0m`

However where did you get that syntax?  I only ask because no of the docs we read showed similar syntax without the ' s.  Would love to read anything I may have missed.

**Comment by charleszipp** [comment]
I think you are missing an equal sign between the `-backend-config` and the actual arg.
When the task sets these up when using the `azurerm` backend, it does so as `-backend-config=storage_account_name=mystorageaccount`. See code [here](https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/master/TerraformCLI/src/terraform-init.ts#L88)

This is also documented in the partial config section in the terraform docs [here](https://www.terraform.io/docs/backends/config.html#partial-configuration)

**Comment by scott-doyland-burrows** [comment]
It also works without an = sign.  At least it does on 0.13.0 (but OP is on 0.11).
In fact on 0.13.0 it fails completely if the quote ' is included.  For me it works without = and without '

Regards,
Scott

**Comment by dox1042** [comment]
For the record we are uing .0.11.14 and it did not work either way still getting 403 erro even do we have env vars pointing to the the right storage and access keys.

**Comment by scott-doyland-burrows** [comment]
Is 403 a different error? If so it sounds like it is may be picking up the storage account and key but is having access issues. I cannot remember all the backend config that needs supplying in the backend block off the top of my head. 

But I had similar issues recently, I ended up testing manually outside Azure DevOps to ensure it worked.  

Could it be missing the subscription ID or something along those lines.

**Comment by dox1042** [comment]
Yea, I made sure that service principal in Azure has access to both the storage and the Resource group over all.  Now the permissions are inherited and not explicit.  

No 403 is not different, it is indeed access denied error.

**Comment by charleszipp** [comment]
@gabrieljoelc @dox1042 I was able to make this work using the following setup. Please note that none of this is not nessarily specific to this task and applies to terraform cli in general. The only exception is the secure files and how those are translated for the terraform cli.

See the following yaml template [here](https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/chzipp/147-self-configured/pipelines/test/init_with_self_configured_backend_inline_with_env.yml). This approach sets the service principal details via an .env file in secure var files. 

> IMPORTANT: this .env file does not contain backend configuration. The format for providing the service principal details and backend are different and do not believe can be provided in a single file. 

Excerpt from the linked template for init configuration. Note the backend configuration is provided to command options. The spn is provided via the secure var file. 

```yaml
- task: charleszipp.azure-pipelines-tasks-terraform-${{ parameters.stage }}.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
  displayName: 'terraform init'
  inputs:
    command: init
    workingDirectory: $(terraform_templates_dir)
    backendType: self-configured
    # The backend must exist, auto-create not possible for self-configured
    commandOptions: -backend-config=resource_group_name=$(my-resource-group-name) -backend-config=storage_account_name=$(my-storage-account-name) -backend-config=container_name=$(my-container-name) -backend-config=key=$(my-blob-file-name)
    # contains service principal env vars (ARM_CLIENT_ID, ARM_CLIENT_SECRET, ARM_SUBSCRIPTION_ID, ARM_TENANT_ID)
    secureVarsFile: $(my-secure-file-id)
```

> NOTE: Resource Group must be provided when authenticating via SPN. If access key is provided in the backend configuration then resource group is not necessary

The secure env file provided to `secureVarsFile` has the following

```sh
ARM_CLIENT_ID=
ARM_CLIENT_SECRET=
ARM_SUBSCRIPTION_ID=
ARM_TENANT_ID=
```
