### ISSUE TITLE
Install step name conflict with another install step 

### ISSUE THREAD

**Issue by Tajjun** [charleszipp/azure-pipelines-tasks-terraform#160]
Hi Charles,

The install step doesn't work because the name conflicts with the other extension name.

Workaround was to use the id of the task:

- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0.5.12

but i don't know how to specificy the version in the azure devops yaml, any idea ?

Thanks

**Comment by charleszipp** [comment]
Hey @Tajjun i am not sure which version you are asking about. If you want to set the version of terraform installed by the task, the yaml property to specify that is `terraformVersion`. 

```yaml
    steps:
    - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0.5.12
      displayName: 'terraform install'
      inputs:
        terraformVersion: 0.13.4
```

If you are asking about the version of the installer task itself, you can change what comes after the `@` symbol to target a different version of the task

```yaml
    steps:
    # Target 0.5.13 version of the task
    - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0.5.13
      displayName: 'terraform install'
      inputs:
        terraformVersion: 0.13.4
```
