### ISSUE TITLE
Double quotes escaping problem on Windows agents

### ISSUE THREAD

**Issue by ksmigiel** [charleszipp/azure-pipelines-tasks-terraform#164]
**Describe the bug**
Problem occurs when I want to call `apply` command with `-replace <address>` command options.
Terraform running on Windows need special escaping to be handled (https://www.terraform.io/docs/cli/commands/state/rm.html#example-remove-a-particular-instance-of-a-resource-using-for_each).

**To Reproduce**
1. Setup pipeline as (include yaml configuration or screenshots of classic ui editor)
``` yaml
- task: TerraformCLI@0
  inputs:
    command: apply
    commandOptions: -auto-approve -replace module.frontdoor.null_resource.https_configuration[\"demo\"]
    workingDirectory: ${{ parameters.directory }}
    environmentServiceName: ${{ parameters.subscription }}
    runAzLogin: true
```
2. Execute pipeline
3. See error

**Agent Configuration**
 - OS: windows2019
 - Hosted
 - Terraform version: default
 - AzureCLI version: default

**Comment by charleszipp** [comment]
@ksmigiel have you tried wrapping the `commandOptions` value in single quotes? Feel free to reopen if that doesnt solve the issue.

```yaml
- task: TerraformCLI@0
  inputs:
    command: apply
    commandOptions: '-auto-approve -replace module.frontdoor.null_resource.https_configuration[\"demo\"]'
    workingDirectory: ${{ parameters.directory }}
    environmentServiceName: ${{ parameters.subscription }}
    runAzLogin: true
```
