### ISSUE TITLE
ailed to load "./terraform.tfplan" as a plan file

### ISSUE THREAD

**Issue by dsfrederic** [charleszipp/azure-pipelines-tasks-terraform#165]
**Describe the bug**

**To Reproduce**
1. Setup pipeline as (include yaml configuration or screenshots of classic ui editor)
2. Execute pipeline
3. See error

**Expected behavior**
Run Terraform plan

```YAML
variables: 
- name: WORKDIR
  value: $(System.DefaultWorkingDirectory)/infra/unit_env
stages:
- stage: TERRAFORM 
  jobs: 
  - job: Init_and_plan
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    - task: TerraformCLI@0
      inputs:
        command: 'init'
        workingDirectory: '$(WORKDIR)'
        backendType: 'azurerm'
        backendServiceArm: 'PLACEHOLDER'
        ensureBackend: true
        backendAzureRmResourceGroupName: 'PLACEHOLDER'
        backendAzureRmResourceGroupLocation: 'westeurope'
        backendAzureRmStorageAccountName: 'PLACEHOLDER'
        backendAzureRmContainerName: 'terraform'
        backendAzureRmKey: 'PLACEHOLDER'

    - task: TerraformCLI@0
      inputs:
        command: 'plan'
        workingDirectory: '$(WORKDIR)'
        environmentServiceName: 'PLACEHOLDER'
        commandOptions: '--var-file ./variables.tfvars --out ./terraform.tfplan -detailed-exitcode'
        publishPlanResults: 'terraform.tfplan'
    
    - bash: |
        echo $TERRAFORM_PLAN_HAS_CHANGES
        echo "##vso[task.setvariable variable=TERRAFORM_PLAN_HAS_CHANGES;isOutput=true;]$TERRAFORM_PLAN_HAS_CHANGES"
        echo "variable value is $(TERRAFORM_PLAN_HAS_CHANGES)"
      name: setVar

    - publish: $(WORKDIR) # Publish complete working directory. https://learn.hashicorp.com/tutorials/terraform/automate-terraform?in=terraform/automation&utm_source=WEBSITE&utm_medium=WEB_IO&utm_offer=ARTICLE_PAGE&utm_content=DOCS#plan-and-apply-on-different-machines
      artifact: terraform


    - task: TerraformCLI@0
      inputs:
        command: 'apply'
        workingDirectory: $(WORKDIR)
        environmentServiceName: 'PLACEHOLDER'
        commandOptions: '"./terraform.tfplan"'
        allowTelemetryCollection: false
```

**Screenshots**

![image](https://user-images.githubusercontent.com/28486949/133606991-00b6e56b-5971-44f5-b211-692955c8dd9e.png)

**Pipeline Logs**
Include logs that help demonstrate the problem. Please make sure to redact any sensitive info such as secrets.

**Agent Configuration**
 - OS: [e.g. ubuntu debian]
 - Hosted/Self Hosted
 - Terraform version used (Default for hosted agent is acceptable)
 - AzureCLI version used (Default for hosted agent is acceptable or N/A)

**Additional context**

**Comment by charleszipp** [comment]
You have too many quotes in your command options try this instead

```yaml
    - task: TerraformCLI@0
      inputs:
        command: 'apply'
        workingDirectory: $(WORKDIR)
        environmentServiceName: 'PLACEHOLDER'
        
        # remove the double quotes
        commandOptions: './terraform.tfplan'
        allowTelemetryCollection: false
```
