### ISSUE TITLE
AzureRm Statefile not being put in 

### ISSUE THREAD

**Issue by gabrielmccoll** [charleszipp/azure-pipelines-tasks-terraform#166]
Hey, there's no error message and everything seems fine but state file is not being used or updated
It applies the config and creates the resources in Azure but , no statefile, and if I run the same pipeline again, it tells me it can't create the resource, it already exists and fails. Showing that it's not seeing the state. 
Terraform 0.13.4
Interestingly the official Microsoft Devlabs seems to have had the same problem for 8 days or so 
![image](https://user-images.githubusercontent.com/25871665/96733051-ee699200-13b0-11eb-85a5-143fc8e615fe.png)

```
      - task: TerraformCLI@0
        displayName: Init Terraform AzureRmBackend
        inputs:
          command: 'init'
          workingDirectory: '$(TerraformWorkingDirectory)'
          backendType: 'azurerm'
          backendServiceArm: 'RLG_SandBox'
          ensureBackend: true
          backendAzureRmResourceGroupName: '$(ResourceGroup)'
          backendAzureRmResourceGroupLocation: 'uksouth'
          backendAzureRmStorageAccountName: '$(StorageAccount)'
          backendAzureRmStorageAccountSku: 'Standard_ZRS'
          backendAzureRmContainerName: '$(StorageAccount)'
          backendAzureRmKey: 'terraform.tfstate'
          allowTelemetryCollection: false

```
![image](https://user-images.githubusercontent.com/25871665/96733666-9ed79600-13b1-11eb-8a64-217fea8e5062.png)
