### ISSUE TITLE
Plugin reinitialization required. Please run "terraform init".

### ISSUE THREAD

**Issue by gurdeepsira** [charleszipp/azure-pipelines-tasks-terraform#172]
Hi,
I have a build pipeline for Terraform which does an init and plan and then a release pipeline which gets artifacts from the build pipeline and then does an init and apply. For the apply task (yaml below), I get this error:

Plugin reinitialization required. Please run "terraform init".

      - task: TerraformCLI@0
        inputs:
          command: 'init'
          workingDirectory: '$(Pipeline.Workspace)'
          backendType: 'azurerm'
          backendServiceArm: 'Pay-As-You-Go(xxx)'
          backendAzureRmResourceGroupName: 'tfstate-rg'
          backendAzureRmStorageAccountName: 'tfstatestoragegs'
          backendAzureRmContainerName: 'tfstatestoragegs-container'
          backendAzureRmKey: 'L9YpLb9ldF3oKVGTeeAH9rf+3/QDat28fWrn8vDYM8PUv+zDXqcn/KXteQpV0mm2nS1Cp404WF8VNt+Pfy3AXQ=='
          allowTelemetryCollection: true

  
      - task: TerraformCLI@0
        inputs:
          command: 'apply'
          workingDirectory: '$(Pipeline.Workspace)'
          environmentServiceName: 'Pay-As-You-Go(xxx)'
          allowTelemetryCollection: true

**Comment by favoretti** [comment]
You need to pass the actual artifact in the command line:
```
- task: TerraformCLI@0
  displayName: 'Apply'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: 'apply'
    commandOptions: '-input=false -parallelism=${{ parameters.parallelism }} -auto-approve tfplan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/apply'
```
