### ISSUE TITLE
Terraform plan has changes

### ISSUE THREAD

**Issue by zoemac11** [charleszipp/azure-pipelines-tasks-terraform#177]
Looking to use the TERRAFORM_PLAN_HAS_CHANGES variable but looks like it is setting it true even when there are no changes made in plan

Using terraform 12.29

![image](https://user-images.githubusercontent.com/41298038/101467398-2cf3e580-393a-11eb-9718-32a6de0ff5af.png)

![image](https://user-images.githubusercontent.com/41298038/101467413-2f563f80-393a-11eb-9e93-004974c85130.png)

**Comment by favoretti** [comment]
Interesting. We use this all over the place and it seems to work. 

![image](https://user-images.githubusercontent.com/805046/102258564-57cbd400-3f0e-11eb-9b02-1773960de00f.png)

**Comment by charleszipp** [comment]
@zoemac11 are you still seeing this after 0.6.4 was released?

**Comment by zoemac11** [comment]
![image](https://user-images.githubusercontent.com/41298038/104903733-4bf18880-5978-11eb-834c-1cfc1c9cd32c.png)
 Yip :(

**Comment by zoemac11** [comment]
Any ideas for this? I would be really handy to be able to use this feature

**Comment by charleszipp** [comment]
@zoemac11 could you provide your yaml configuration for the terraform plan task? If you cannot provide that, could you let me know if you are providing the [-detailed-exitcode](https://www.terraform.io/docs/cli/commands/plan.html#detailed-exitcode) option in command options?

It looks like there might be a condition where this could happen if the `-detailed-exitcode` option is not provided in commandOptions. https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/6eff59b1607c87776de9aaf74a56f51294d625e2/tasks/terraform-cli/src/commands/tf-plan.ts#L61

**Comment by zoemac11** [comment]
This is my yaml task I'm running

```
- task: TerraformCLI@0
        displayName: 'Run Terraform Plan'
        inputs:
          command: plan
          workingDirectory: 'azure/dev'
          environmentServiceName:  'Owner'
          commandOptions: '-out=plan.tfplan'
          allowTelemetryCollection: false

```

Adding `-detailed-exitcode` solved the problem, thanks!
