### ISSUE TITLE
Terraform init not working on version 0.6.4

### ISSUE THREAD

**Issue by harugrin** [charleszipp/azure-pipelines-tasks-terraform#185]
Since the last deploy of the extension (08/JAN 17h30 BRT) we are getting the error below:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/1040099/104076655-795e6980-51f5-11eb-96ae-9ff24a8826a9.png)

Our code is:
- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(Pipeline.Workspace)/apim'
    commandOptions: '-backend-config="$(Pipeline.Workspace)/apim/backend.tfvars"'
    backendType: 'selfConfigured'
    allowTelemetryCollection: true  

The file backend.tfvars exists and the command works manually in the agent with with de configured account:

![Captura de Tela 2021-01-08 às 21 08 59](https://user-images.githubusercontent.com/1040099/104076785-db1ed380-51f5-11eb-9d5d-86847b163dbd.png)

**Comment by garentsen** [comment]
Hello, We have the same issue here.


![image](https://user-images.githubusercontent.com/54887486/104158266-454d9900-53ed-11eb-9865-cf5914b8cce2.png)


Br
Guido

**Comment by pbarbero** [comment]
Hello,

same for us

![image](https://user-images.githubusercontent.com/5489928/104160611-b42cf100-53f1-11eb-9fef-24405f24070c.png)

our code is:

```
 - task: TerraformCLI@0
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/${{ parameters.TeamProject }}'
        commandOptions: '-backend-config="secret_key=${{ parameters.s3_secret_key }}"'
        backendType: 'selfConfigured'
        allowTelemetryCollection: true
```

with provider.tf configuration as follows

```
terraform {
  required_version = ">= 0.12"
  backend "s3" {
  bucket = "xx"
  key    = "xx.tfstate"
  region = "xx"
	access_key = "XXX"
	role_arn = "XX"
	external_id = "XXX"
  }
```
