### ISSUE TITLE
Terraform plan fails to detect infrastructure changes

### ISSUE THREAD

**Issue by aymen-segni** [charleszipp/azure-pipelines-tasks-terraform#188]
Hello,

We have the following pipeline

```
stages:
  - stage: Module
    displayName: Common Module
    jobs:
    # Common Module
    - job: CommonModule
      displayName: Deploy the Terraform Common module
      pool:
        vmImage: $(vmImageName)
      steps:
      - task: InstallSSHKey@0
        displayName: 'Install an SSH key'
        inputs:
          knownHostsEntry: $(sshKnownHostsEntry)
          sshPublicKey: $(sshPublicKey)
          sshKeySecureFile: id_rsa
      - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
        displayName: 'Use Terraform $(terraformVersion)'
        inputs:
          terraformVersion: $(TF_VERSION)
      - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
        displayName: 'terraform init'
        inputs:
          command: init
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/common'
          backendType: azurerm
          backendServiceArm: $(azureSubscriptionServiceConnectionName)
          ensureBackend: true
          backendAzureRmResourceGroupLocation: $(location)
          backendAzureRmResourceGroupName: $(tfStateResourceGroupName)
          backendAzureRmStorageAccountName: $(tfStateAzureStorageAccountName)
          backendAzureRmStorageAccountSku: $(tfStateAzureStorageAccountSku)
          backendAzureRmContainerName: $(tfStateContainerName)
          backendAzureRmKey: 'common.tfstate'
      - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
        displayName: 'terraform validate'
        inputs:
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/common'
      
      - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
        displayName: 'terraform plan'
        inputs:
          command: plan
          workingDirectory: $(System.DefaultWorkingDirectory)/terraform/common
          environmentServiceName: $(azureSubscriptionServiceConnectionName)
          commandOptions: -out=$(System.DefaultWorkingDirectory)/terraform/common/terraform.tfplan -detailed-exitcode
```

This is going to be applied in a new subscription, the module initialization and validation step works fine, but the terraform plan task shows no output even though the step is to deploy some common Azure resources to a new environment.
I actually get the following output

```
/opt/hostedtoolcache/terraform/0.13.4/x64/terraform plan -out=/home/vsts/work/1/s/terraform/common/terraform.tfplan -detailed-exitcode
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Finishing: terraform plan
```
I don't know if this is a bug or I'm doing something wrong, can you get a look please ?
