### ISSUE TITLE
terraform-cli task does not finish when running on vmss self-hosted azure devops agent.

### ISSUE THREAD

**Issue by yesoos** [charleszipp/azure-pipelines-tasks-terraform#190]
Terraform task does not end when using Virtual Machine Scale Set self-hosted azure devops agents. I have vmss of ubuntu machines as self-hosted agents - terraform-cli tasks are successful (you can see in log) - but the pipeline task never finishes - it times out after 60 minutes. 

The same tasks using bash task pipeline - or on VM self-hosted agent work simply fine. There is nothing in the log.

**Comment by charleszipp** [comment]
@yesoos could you share a sample yaml configuration that reproduces the issue? Also, have you attempted to run terraform commands directly using bash on these agents? This would help determine if the issue is with terraform itself or this task.

**Comment by yesoos** [comment]
@charleszipp as an example:

Bash command work fine on VMSS

          - bash: 'terraform init -reconfigure -backend-config="storage_account_name=$(TfStorageAccountName)" -backend-config="container_name=$(TfStateContainerName)" -backend-config="key=$(TfStateNameGlobal)" -backend-config="access_key=$(TfStorageAccountKey)"'
            workingDirectory: "$(Pipeline.Workspace)/infra/$(stage)/$(context)"
            displayName: "terraform init (bash)"

Following terraform-cli task also works, but after a successful run it just waits and times out after 60 minutes:

          - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
            displayName: "terraform init"
            inputs:
              command: init
              workingDirectory: "$(Pipeline.Workspace)/infra/$(stage)/$(context)"
              commandOptions: '-reconfigure -backend-config="storage_account_name=$(TfStorageAccountName)" -backend-config="container_name=$(TfStateContainerName)" -backend-config="key=$(TfStateNameGlobal)" -backend-config="access_key=$(TfStorageAccountKey)"'

Strangely enough, the same task works simply fine when running it on a simple VM agent.

**Comment by loispostula** [comment]
Hi @charleszipp we are experiencing the same issues here. Here a simple Yaml Snippet that creates  the issue:
```yaml
trigger: none

pool: On Prem Windows Builder

variables:
  - name: terraform_backend_file_name
  - name: terraform_templates_dir
    value: $(Build.SourcesDirectory)

jobs:
  - job: terraform
    displayName: Create Subscriptions with Terraform
    steps:
      - task: DownloadSecureFile@1
        name: terraformBackend
        displayName: 'Download Terraform Backend File'
        inputs:
          secureFile: $(terraform_backend_file_name)
      - task: PowerShell@2
        inputs:
          workingDirectory: $(terraform_templates_dir)
          targetType: inline
          script: |
            terraform init
      - task: TerraformCLI@0
        displayName: Initialize Terraform
        inputs:
          workingDirectory: $(terraform_templates_dir)
          command: init
          environmentServiceName: SC_MGMT_AUTOMATION
          commandOptions: '-backend-config=$(terraformBackend.secureFilePath)'
```

The `Powershell` step is working fine while the `TerraformCli@0` hangs indefinitely.

I have enabled the System Diagnostics logs and everything looks fine, the last logs from the step looks like this:
```bash
##[debug]command=init
##[debug]executed command 'init'
##[debug]set TERRAFORM_LAST_EXITCODE=0
##[debug]commandProcessed: ##vso[task.setvariable variable=TERRAFORM_LAST_EXIT_CODE;isOutput=false;isSecret=false;]0
```

The version of `azure-pipelines-tasks-terraform` is 0.7.3 and the version of the agent is `2.195.1`
