### ISSUE TITLE
feature request: Add support for variable groups, specifically linking secure variables from KeyVault.

### ISSUE THREAD

**Issue by andrewCluey** [charleszipp/azure-pipelines-tasks-terraform#222]
Not a bug, but an extra feature that could be really useful.

**Overview**
Currently, secure variable files can be imported into the TerraformCli task. However, these are static files so it introduces some additional overhead to keep the file up to date (for example when SPN secrets rotate).

If the terraform-cli-task could make use of Variable Groups (specifically the KeyVault integration), it will automatically bring through the updated values direct from keyVault. Meaning any automation already used to rotate SPN secrets can still be used.

**Proposed behaviour**
New field that accepts a variable group name (pipeline variable / text / dropdown). All KV integration is done within the Variable Groups itself. 

Once the group is added, the secrets in the Variable Group should be set as environment variables for use by Terraform. 
This would provide another option for authenticating Terraform (using the 'ARM_..' environment variable) or for setting input parameters (TF_VAR_...). 

Example:
ARM_CLIENT_ID
ARM_CLIENT_SECRET
ARM_TENANT_ID
TF_VAR_secret

**Comment by charleszipp** [comment]
@andrewCluey I think this can be accomplished today in YAML using Azure Pipelines built in environment variable support. Every type of step (bash, script, task, etc) support configuring a map of env variables. So i think you can do something like

```yaml
- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
  displayName: 'terraform apply'
  env: 
    ARM_CLIENT_ID: $(my_client_id_var)
    ARM_CLIENT_SECRET: $(my_client_secret_var)
    ARM_TENANT_ID: $(my_tenant_id_var)
    TF_VAR_secret: $(my_tf_secret_var)
  inputs:
    command: apply
    workingDirectory: $(test_templates_dir)
    commandOptions: '$(System.DefaultWorkingDirectory)/terraform.tfplan'
```

The `$(my_client_id_var)` can come from a variable group that is referenced earlier on in your yaml. Variable groups can be linked to key vault secrets.

```yaml
stages:
- stage: my_stage
  variables:
    - group: my_var_group
```

Hopefully this helps, feel free to reopen if this does not solve what you needed.
