### ISSUE TITLE
Conflict installer task with Microsoft extension

### ISSUE THREAD

**Issue by philthynz** [charleszipp/azure-pipelines-tasks-terraform#233]
I started using this extension today. Really like it, much better than the Microsoft task. However, a lot of companies are going to be using the Microsoft task. Mainly because it's not 3rd party. If they install the extension from charleszipp, all the previous pipelines are going to break.

The installer task has the same name:

```
    - task: TerraformInstaller@0 # <-- Microsoft task
      inputs:
        terraformVersion: '0.12.3'
    - task: TerraformInstaller@0 # <-- charleszipp task
      inputs:
        terraformVersion: 'latest'
```

Yes we can get around this by specifying `- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0`, but this doesn't help all the other 100's of pipelines that use the Microsoft task.

I propose @charleszipp the installer task is renamed to avoid conflicts in other organizations.
