### ISSUE TITLE
Error: Input required: backendAzureRmResourceGroupLocation

### ISSUE THREAD

**Issue by pavelpikatamcs** [charleszipp/azure-pipelines-tasks-terraform#235]
**Describe the bug**
The task seem to require `backendAzureRmResourceGroupLocation` input after latest release? Since we cannot control the version of individual tasks & extensions, all our pipelines are broken. 

**To Reproduce**
```
  - task: TerraformCLI@0
    displayName: 'Terraform init'
    inputs:
      command: 'init'
      workingDirectory: '${{ parameters.workingDirectory }}'
      backendType: 'azurerm'
      backendServiceArm: '${{ parameters.subscription }}'
      backendAzureRmResourceGroupName: '%rg-name%'
      backendAzureRmStorageAccountName: '%account-name%'
      backendAzureRmContainerName: '%container-name%'
      backendAzureRmKey: '${{ parameters.backendKey }}'
      allowTelemetryCollection: false
```

**Expected behavior**
I would expect the task to work as before without requiring `backendAzureRmResourceGroupLocation` input

**Pipeline Logs**
```
Starting: Terraform init
==============================================================================
Task         : Terraform CLI
Description  : Execute terraform cli commands
Version      : 0.7.0
Author       : Charles Zipp
Help         : 
==============================================================================
C:\hostedtoolcache\windows\terraform\1.0.1\x64\terraform.exe version
Terraform v1.0.1
on windows_amd64

Your version of Terraform is out of date! The latest version
is 1.1.2. You can update by downloading from https://www.terraform.io/downloads.html
C:\hostedtoolcache\windows\terraform\1.0.1\x64\terraform.exe init -backend-config=storage_account_name=*** -backend-config=container_name=*** -backend-config=key=*** -backend-config=resource_group_name=*** -backend-config=subscription_id=*** -backend-config=tenant_id=*** -backend-config=client_id=*** -backend-config=client_secret=***

Initializing the backend...

Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding latest version of hashicorp/random...
- Finding hashicorp/azurerm versions matching "2.65.0"...
- Finding hashicorp/azuread versions matching "1.4.0"...
- Installing hashicorp/random v3.1.0...
- Installed hashicorp/random v3.1.0 (signed by HashiCorp)
- Installing hashicorp/azurerm v2.65.0...
- Installed hashicorp/azurerm v2.65.0 (signed by HashiCorp)
- Installing hashicorp/azuread v1.4.0...
- Installed hashicorp/azuread v1.4.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!
##[error]Error: Input required: backendAzureRmResourceGroupLocation
Finishing: Terraform init
```

**Agent Configuration**
 - OS: both Ubuntu 20.04 & Windows Server 2019
 - both Hosted & Self Hosted
 - Terraform version used: 1.0.1
 - AzureCLI version used: N/A

**Additional context**
