### ISSUE TITLE
Azure Devops Service Connection Failing(Error building ARM Config: obtain subscription from Azure CLI)

### ISSUE THREAD

**Issue by sc2317** [charleszipp/azure-pipelines-tasks-terraform#237]
Hi,
I am getting below error while using azurerm service connection. Code works fine if I use environment variables instead of this extension.
Error: Error building ARM Config: obtain subscription from Azure CLI: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.

Below is the yaml file that I am using to use this extension. Any help would be much appreciated.

trigger:
  branches:
    include:
    - '*'
    # - 'Azure-Pipelines'
  paths:
    include:
    # - 'demo/pipelines/*'
    - '/*'
variables:
  # There must be an Azure Service Connection with that name defined in your Azure DevOps settings. See https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops
  serviceConnection: 'armserviceconnection'
  # Terraform settings
  terraformWorkingDirectory: '$(System.DefaultWorkingDirectory)/core'
  terraformVersion: '1.1.2'
stages:
- stage: TerraformContinuousIntegration
  displayName: Terraform Module - CI
  jobs:
  - job: TerraformContinuousIntegrationJob
    displayName: TerraformContinuousIntegration - CI Job
    pool:
      vmImage: ubuntu-20.04
    steps:
    # Step 1: run the Checkov Static Code Analysis
    - bash: $(System.DefaultWorkingDirectory)/azure-pipelines/checkov.sh $(terraformWorkingDirectory)
      displayName: Checkov Static Code Analysis
    # Step 2: install Terraform on the Azure Pipelines agent
    - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: $(terraformVersion)
    # Step 3: run Terraform init to initialize the workspace
    - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
      displayName: 'Run terraform init'
      inputs:
        command: init
        workingDirectory: $(terraformWorkingDirectory)
    # Step 4: run Terraform validate to validate HCL syntax
    - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
      displayName: 'Run terraform validate'
      inputs:
        command: validate
        workingDirectory: $(terraformWorkingDirectory)
    # Step 5: run Terraform plan to validate HCL syntax
    - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
      displayName: 'Run terraform plan'
      inputs:
        command: plan
        workingDirectory: $(terraformWorkingDirectory)
        environmentServiceName: $(serviceConnection)
        runAzLogin: true

**Comment by charleszipp** [comment]
I dont believe azure pipelines will let you use a variable for a service connection. This is a limitation in azure pipelines if I remember correctly. I would suggest testing it with the service connection provided as literal (instead of variable) and see if that resolves the issue.

**Comment by sc2317** [comment]
@charleszipp 
I am following below article to understand the yaml usage to run terraform tasks using this extension. In this article they have specified service connection as variable.

https://docs.microsoft.com/en-us/azure/developer/terraform/best-practices-integration-testing
https://github.com/Azure/terraform/blob/master/samples/integration-testing/src/azure-pipeline.yaml

Also, further adding one more thing. This is failing at task 'terraform init' itself so it does not move to remaining tasks.

**Comment by sc2317** [comment]
I just tested using service connection as literal instead of variable but it also fails with same error.

**Comment by charleszipp** [comment]
can you share a screenshot of the service connection being used with sensitive values redacted?

**Comment by sc2317** [comment]
@charleszipp 

Please see below screenshot. 

![](https://user-images.githubusercontent.com/79924812/147831650-840c6b4e-4077-4e8c-90c7-e39f5c882dad.png)

Also, I want to highlight one more point is that terraform state file is stored in azure blob storage(Already Created) in different subscription and this is the subscription ID that is provided in the service connection mentioned above. Error(Error: Error building ARM Config: obtain **subscription**(This is which has tf state file) from Azure CLI) that I provided earlier comes for this subscription. 
Service principal used has rights on all the subscriptions including the providers one. I see one of your other link (https://github.com/charleszipp/azure-pipelines-tasks-terraform/issues/14) where you suggest using ARM_ACCESS_KEY for storage account that has tf state file so that it works without any issue. 
However, I am confused then which subscription ID should I provide in the service connection because this service connection will be used to deploy resources on multiple subscriptions.

**Comment by charleszipp** [comment]
@sc2317 The other users that have experienced this issue worked around this by setting the subscription id in command options during the init step. I pulled this example from the previous instance of this github repo. The subscription id supplied in command options should be the backend storage account's subscription. This will override the subscription provided in the service connection. The subscription provided in the service connection should be the subscription where terraform will be deploying resources.

Also please note that the task only supports the service principal (manual) service connection type. The service connection on the right side of the screen shot (provides only key and tenant) is not supported. However, it should not be needed if you use the workaround suggested.

```yaml
      - task: TerraformCLI@0
        displayName: terraform init
        inputs:
          command: init
          workingDirectory: '$(System.DefaultWorkingDirectory)/components/${{ parameters.component }}'
          backendType: azurerm
          backendServiceArm: '${{ parameters.service_connection }}'
          backendAzureRmResourceGroupName: 'tamops12345'
          backendAzureRmStorageAccountName: 'tamops12345'
          backendAzureRmContainerName: '${{ parameters.backendAzureRmContainerName }}'
          backendAzureRmKey: '${{ parameters.component }}.tfstate'  
          commandOptions: '-backend-config=subscription_id=xxxx-xxxx-xxxx-xxxxx' ****
```

`commandOptions: '-backend-config=subscription_id=xxxx-xxxx-xxxx-xxxxx' ****` is the key part of the configuration that allows this to work
