### ISSUE TITLE
Empty Terraform Plan view

### ISSUE THREAD

**Issue by aimar-worth** [charleszipp/azure-pipelines-tasks-terraform#237]
Hello,

Sorry if I ask a silly question but is terraform plan view in Azure DevOps not ready or why I'm not able to see anything in there?

![image](https://user-images.githubusercontent.com/46780510/109778841-93209980-7c05-11eb-8095-270bf2783474.png)

My task is as following
```
- task: TerraformCLI@0
  displayName: 'terraform plan'
  inputs:
      command: plan
      environmentServiceName: xxx-xxx-xxx-$(workspace)
      commandOptions: '-out=$(System.DefaultWorkingDirectory)/terraform.tfplan -detailed-exitcode'
      workingDirectory: deployment
      allowTelemetryCollection: false
      publishPlanResults: true
```

Should this Terraform Plan view pick this up somehow or should I publish this some way?
Didn't find anything from the documentation or from the issues.

Thanks!
