### ISSUE TITLE
Ensure Backend has issues with recently destroyed infrastructure

### ISSUE THREAD

**Issue by amoore-incomm** [charleszipp/azure-pipelines-tasks-terraform#247]
Hello!

ISSUE: Ensure backend sometimes fails to create the storage account

YML setup: 
```
trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'
```
Replication:
I am using your Auzre terraform pipeline module similiar to the below.
 
While development of this code is ongoing, i see myself manually taking down the Resource group via the Azure UI, and immediately redeploying the pipeline that contains the below snippet.. I think this is the cause of my issue...usually if i let the Resource group stay dead for awhile, i do not have this issue.  Obviously low priority as i have a workaround (ie patience)

```
    - task: TerraformCLI@0
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra/dev'
        backendType: 'azurerm'
        backendServiceArm: '$(DisbursementsSubscriptionId)'
        ensureBackend: true
        backendAzureRmResourceGroupName: 'tfrepubsim'
        backendAzureRmResourceGroupLocation: '$(Location)'
        backendAzureRmStorageAccountName: 'tfrepubsim'
        backendAzureRmContainerName: 'tfrepubsim'
        backendAzureRmKey: 'dev.terraform.tfstate'
        allowTelemetryCollection: true
      displayName: "Terraform Init"
 ```
Occasionally (for reasons unknown) i get this during the above tf init. It will succesfully build the Resource group for me, but fails to build the Storage Account.  Usually, letting the Resource Group stay dead for 10 minutes before i redeploy a pipeline solves the issue.

```
Starting: Terraform Init
==============================================================================
Task         : Terraform CLI
Description  : Execute terraform cli commands
Version      : 0.6.13
Author       : Charles Zipp
Help         : 
==============================================================================
/opt/hostedtoolcache/terraform/0.14.7/x64/terraform version
Terraform v0.14.7

/usr/bin/az login --service-principal -t *** -u *** -p ***
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "***",
    "id": [redacted],
    "isDefault": true,
    "managedByTenants": [],
    "name": "[redacted]",
    "state": "Enabled",
    "tenantId": "***",
    "user": {
      "name": "***",
      "type": "servicePrincipal"
    }
  }
]

/usr/bin/az account set -s [redacted]

/usr/bin/az group create --name dev-ids-repub-sim-rg --location eastus2
{
  "id": "/subscriptions/[redacted]/resourceGroups/dev-ids-repub-sim-rg",
  "location": "eastus2",
  "managedBy": null,
  "name": "dev-ids-repub-sim-rg",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null,
  "type": "Microsoft.Resources/resourceGroups"
}

/usr/bin/az storage account show --name devidsrepubsimsa --resource-group dev-ids-repub-sim-rg
ERROR: (StorageAccountNotFound) The storage account devidsrepubsimsa was not found.

##[error]Error: ERROR: (StorageAccountNotFound) The storage account devidsrepubsimsa was not found.

##[error]Error: ERROR: (StorageAccountNotFound) The storage account devidsrepubsimsa was not found.

##[error]Error: ERROR: (StorageAccountNotFound) The storage account devidsrepubsimsa was not found.

Finishing: Terraform Init

```
