### ISSUE TITLE
`terraform apply [plan]` gives an error when used together with `publishPlanResults`

### ISSUE THREAD

**Issue by gdespoulain** [charleszipp/azure-pipelines-tasks-terraform#249]
### Bug Description

Hello! :)

I'm using `terraform plan -out="terraform.tfplan"` in one stage, and then applying said plan using the plan text file (passed as an artifact) in another stage: `terraform apply terraform.tfplan`. During the plan task I use the _publishPlanResults_ as option.

The plan is valid and shown properly in the **Terraform Plan** tab. However, I get this error during apply:

```
Error: Failed to load "terraform.tfplan" as a plan file
Error: zip: not a valid zip file
```

I researched a bit and found out it seems to be a problem for Terraform to process the plan after it has been used by _publishPlanResults_. At least it's the theory that has been discussed at the end of this thread: https://github.com/hashicorp/terraform/issues/22396 where they could also reproduce the problem.

### To Reproduce

**1. Setup pipeline as:**

```
stages:
  - stage: Plan
    jobs:
      - job: Plan
        steps:
          - task: TerraformCLI@0
            ...
            inputs:
              command: plan
              publishPlanResults: plan.tfplan
              ...
          - publish:
              artifact: plan
              ...

  - stage: Apply
    ...
    jobs:
      - job: Apply
        ...
        steps:
          - download: ...
          - task: TerraformCLI@0
            inputs:
              command: apply
              commandOptions: '--input=false $(Pipeline.Workspace)/plan/plan.tfplan'
```

**2. Execute pipeline**

Let both stages run. The plan is saved accordingly and available in apply stage.

3. See error

The error appears in the log. It's gone when I remove the _publishPlanResults_ option.

```
Error: Failed to load "terraform.tfplan" as a plan file
Error: zip: not a valid zip file
```

### Expected behavior

I would like to use both the _publishPlanResults_ option and a saved plan :)

### Agent Configuration

 - VM: ubuntu
 - Terraform version: 1.1.4

Thank you!
