### ISSUE TITLE
Allow environmentServiceName and runAzLogin to be set on init to enable service principle login

### ISSUE THREAD

**Issue by dvdvorle** [charleszipp/azure-pipelines-tasks-terraform#253]
**Describe the bug**
I'd like to do

```yml
- task: TerraformCLI@0
  inputs:
    command: init
    environmentServiceName: $(serviceconnection)
    runAzLogin: true
```
But this isn't allowed, instead I have to fall back to AzureCLI

```yml
- task: AzureCLI@2
  inputs:
    azureSubscription: $(serviceconnection)
    scriptType: bash
    scriptLocation: inlineScript
    addSpnToEnvironment: true
    inlineScript: |
      set -eu
      subscriptionId=$(az account show --query id -o tsv)

      export ARM_CLIENT_ID=$servicePrincipalId
      export ARM_CLIENT_SECRET=$servicePrincipalKey
      export ARM_SUBSCRIPTION_ID=$subscriptionId
      export ARM_TENANT_ID=$tenantId

      terraform init
```

**To Reproduce**
1. Setup pipeline as
```yml
- task: TerraformCLI@0
  inputs:
    command: init
    environmentServiceName: $(serviceconnection)
    runAzLogin: true
```
2. Have a terraform backend in your repository like
```terraform
terraform {
  backend "azurerm" {
    resource_group_name  = "rg-name"
    storage_account_name = "stwhatever"
    container_name       = "terraformstate"
    key                  = "some.terraform.tfstate"
  }
}
```
3. Manually provision an azure storage account such as defined in step 2
4. Execute pipeline
5. See YAML error
--- 
If I use the selfConfigured backendType in step 1, like this: 
```yml
- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'selfConfigured'
```
Then I get the following error in 5.
```
Initializing the backend...

Error: Error building ARM Config: obtain subscription() from Azure CLI: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1
```

**Expected behavior**
Succesful initialisation

**Agent Configuration**
 - OS: ubuntu
 - Hosted
 - Terraform version used: latest (0.14.8)
 - AzureCLI version used: default

P.s. great extension, way better than the Microsoft default one, this addition would make it perfect :-)
