### ISSUE TITLE
Make backend configuration optional when using backend type `azurerm`

### ISSUE THREAD

**Issue by charleszipp** [charleszipp/azure-pipelines-tasks-terraform#254]
Given I have the following terraform template

```terraform
terraform {
  backend "azurerm" {
    resource_group_name  = "rg-name"
    storage_account_name = "stwhatever"
    container_name       = "terraformstate"
    key                  = "some.terraform.tfstate"
  }
}
```

I would like to be able to execute terraform init with a service connection but, no backend configuration since its already provided in the template

```yaml
- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'my-service-connection'
```

** Note; In this case, ensureBackend may not be possible given it needs the storage sku and location to create properly. The user would need to provide the SKU and Location for ensureBackend to work.

Replaces #253
