### ISSUE TITLE
publishPlanResults results in a blank Terraform Plan view

### ISSUE THREAD

**Issue by hallgeirl** [charleszipp/azure-pipelines-tasks-terraform#255]
Hi!
I'm trying to get some output to the terraform plan view.. The view just shows:
```No terraform plans have been published for this pipeline run. The terraform cli task must run plan with publishPlanResults: string (where string represents the plan name) to view plans.```

I have set the `publishPlanResults` input on the plan task:

```
    - task: TerraformCLI@0
      displayName: 'terraform plan'
      inputs:
          command: plan
          environmentServiceName: 'Dev'
          workingDirectory: 'team-dev-spaces/platform/infrastructure/test-infra-deploy/terraform'
          runAzLogin: true
          publishPlanResults: 'testinfra'
          commandOptions: '-out=$(Pipeline.Workspace)/testinfra.tfplan -detailed-exitcode'
```

I also set System.Debug=true and inspected the debug output of the plan command. I could not see any obvious errors. I have attached the file to this issue.
[tfoutput.txt](https://github.com/charleszipp/azure-pipelines-tasks-terraform/files/6220686/tfoutput.txt)

I'm also publishing the plan result as an artifact (not sure if that is needed):
```
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact: terraform-plans'
      inputs:
        targetPath: $(Pipeline.Workspace)/testinfra.tfplan
        artifact: 'terraform-plans'
```

Is there something I am missing? Does the value in the publishPlanResults input need to have a particular value, matched to something else? I couldn't find anything about this in the docs.

I'm using the latest version of the extension (0.6.15), and the latest version of Terraform (0.14.9). The pipeline is running on an Ubuntu 18.04 agent, and I'm using Azure Storage as the backend storage.

Is this a bug, or a user error (me)? :-)
