### ISSUE TITLE
TF_OUT_ pipeline variables cant be assigned to a variable?

### ISSUE THREAD

**Issue by mjoemar53** [charleszipp/azure-pipelines-tasks-terraform#263]
I'm trying to pass out the `TF_OUT_` variable to other steps/jobs. 
So I tried assigning its value to a `$test` variable but the value of the output wasn't passed.

```yml
- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
  displayName: 'terraform apply'
  inputs:
    command: apply
    workingDirectory: '$(Pipeline.Workspace)/${{parameters.artifact}}'
    commandOptions: main.tfplan
  enabled: true 

- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
  displayName: 'terraform output'
  inputs:
    command: output
    workingDirectory: '$(Pipeline.Workspace)/${{parameters.artifact}}'
  enabled: true

- powershell: |
    Write-Host "$(TF_OUT_agentpublic_ip)" ##this prints the correct IP
    $test = $TF_OUT_agentpublic_ip
    Write-Host "$test" ##this does not print anything at all
    Write-Host "##vso[task.setvariable variable=AGENT_PIP;isOutput=true]$(TF_OUT_agentpublic_ip)" ## other jobs are getting blank
  name: outputVar
```
I tried getting the type of the `$test` variable and it was a null.

Agent Used: Microsoft Hosted (windows2019)
Terraform Version: 0.14.7

**Comment by charleszipp** [comment]
Have you tried including the parenthesis in the line that assigns `$test`? Right now you have ` $test = $TF_OUT_agentpublic_ip`. Azure Pipelines wont evaluate that as a pipeline var due to the lack of parenthesis. Try  $test = "$(TF_OUT_agentpublic_ip)". 

FYI if there was an issue with the this extension, the first line that prints the output value would not work. This appears to be more of an azure pipelines yaml usage question/issue.

**Comment by mjoemar53** [comment]
I tried it out and this was the result.

![image](https://user-images.githubusercontent.com/61579441/114590965-f51bf680-9cbb-11eb-9526-4a0ca71b16d9.png)

Yaml
```yaml
 - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
    displayName: 'terraform output'
    inputs:
      command: output
      workingDirectory: '$(Pipeline.Workspace)/${{parameters.artifact}}'
    enabled: true 
  
  - powershell: |
      Write-Host "$(TF_OUT_agentpublic_ip)"
      $test = $(TF_OUT_agentpublic_ip)
      Write-Host "$test"
```
