### ISSUE TITLE
multi-stage pipeline publishPlanResults

### ISSUE THREAD

**Issue by ghost** [charleszipp/azure-pipelines-tasks-terraform#268]
**Describe the bug**
When using a multi-stage pipeline, which has more than 1 terraform plan run, when using publishPlanResults (all with different names), no terraform plan results are published. I have run a single stage and it works fine

**To Reproduce**
1. Setup pipeline as (include yaml configuration or screenshots of classic ui editor)

```
stage: BaseInfrastructureUpdates
    jobs:
       - job:
         steps:
              - task: TerraformCLI@0
                 displayName: ${{ parameters.displayName }}
                 inputs:
                     environmentServiceName: **
                     providerServiceAws: **
                     providerAwsRegion: eu-west-1
                     backendType: aws
                     backendServiceAws: **
                     publishPlanResults: ${{ parameters.publishPlanResults }}
stage: Microservices
    jobs:
       - job:
         steps:
              - task: TerraformCLI@0
                 displayName: ${{ parameters.displayName }}
                 inputs:
                     environmentServiceName: **
                     providerServiceAws: **
                     providerAwsRegion: eu-west-1
                     backendType: aws
                     backendServiceAws: **
                     publishPlanResults: ${{ parameters.publishPlanResults }}
```
2. Execute pipeline
3. No plans results

**Expected behavior**
All terraform plans to be shown

**Screenshots**
![Screenshot 2022-04-07 at 08 51 15](https://user-images.githubusercontent.com/47382755/162148455-b5ab8c8e-5d5d-4d69-89d4-601f5b4b9697.png)

**Agent Configuration**
 - OS: [e.g. ubuntu debian]: ubuntu-latest
 - Hosted/Self Hosted: Hosted (ubuntu-latest)
 - Terraform version used: latest (v1.1.7)
 - AzureCLI version used (Default for hosted agent is acceptable or N/A): N?A
