### ISSUE TITLE
TERRAFORM_PLAN_HAS_DESTROY_CHANGES variable is not being set when there are destroy changes in the plan

### ISSUE THREAD

**Issue by jmyers82** [charleszipp/azure-pipelines-tasks-terraform#280]
**Describe the bug**
When using the terraform cli for a plan and adding the -publishPlanResults, followed by a terraform cli show command only populates TERRAFORM_PLAN_HAS_CHANGES variable and not the TERRAFORM_PLAN_HAS_DESTROY_CHANGES variable. 

**To Reproduce**
1. Setup pipeline as follows:
```
- task: TerraformCLI@0
  displayName: Terraform Plan
  inputs:
    command: plan
    workingDirectory: ${{ parameters.working_dir }}
    publishPlanResults: terraform.tfplan
    commandOptions: -lock-timeout 5m  -input=false -detailed-exitcode -out terraform.tfplan

- task: TerraformCLI@0
  displayName: Terraform Show 
  inputs:
    command: show
```
3. Execute pipeline
No error, just not getting output variable as expected.  I did get an error when I attempted to echo out the var that didnt existed. 
```
TERRAFORM_PLAN_HAS_CHANGES==true
TERRAFORM_PLAN_HAS_DESTROY_CHANGES : The term 'TERRAFORM_PLAN_HAS_DESTROY_CHANGES' is not recognized as the name of a cmdlet, function, script file, or operable program.
```
5. The warnings in the pipeline indicate a destroy change:
![image](https://user-images.githubusercontent.com/25810385/186926603-39c66b3e-289d-459d-973e-06909bf0b0a6.png)

Setup a powershell task and did a get-childitem Env:
There is no env var for destroy changes?

TEMP                           C:\Users\VSSADM~1\AppData\Local\Temp                                                    
TERRAFORM_LAST_EXITCODE        0                                                                                       
TERRAFORM_PLAN_HAS_CHANGES     true                                                                                    
TF_BUILD                       True   

**Expected behavior**
I expected there to be both variables set to true
TEMP                           C:\Users\VSSADM~1\AppData\Local\Temp                                                    
TERRAFORM_LAST_EXITCODE        0                                                                                       
TERRAFORM_PLAN_HAS_CHANGES     true  
TERRAFORM_PLAN_HAS_DESTROY_CHANGES     true                                                                                    
TF_BUILD                       True   

**Screenshots**

**Pipeline Logs**
Include logs that help demonstrate the problem. Please make sure to redact any sensitive info such as secrets.

**Agent Configuration**
 - OS: windows-latest
 - Hosted
 - Terraform version : 1.1.1
 - AzureCLI version : default on agent

**Additional context**
