### ISSUE TITLE
Terraform init task not masking Service Connection secret

### ISSUE THREAD

**Issue by darrens280** [charleszipp/azure-pipelines-tasks-terraform#336]
When using an Azure yaml pipeline to perform Terraform init task (which calls from a yaml template file), the Azure Service Connection secret is getting displayed as plain text in the pipeline job results.

**To Reproduce**
1. Setup pipeline as 
```
steps:
  - task: TerraformCLI@0
    displayName: "terraform init"
    inputs:
      command: "init"
      workingDirectory: $(workingDirectory)
      backendType: "azurerm"
      ensureBackend: false
      backendServiceArm: $(azureDevOpsServiceConnectionName)
      backendAzureRmResourceGroupName: $(backend-resource-group)
      backendAzureRmStorageAccountName: $(backend-storage-account)
      backendAzureRmContainerName: $(backend-blob-container)
      backendAzureRmKey: $(statefile)
      allowTelemetryCollection: $(useTelemetery)
```
3. Execute pipeline
4. See error (scroll to the right) - The `client_id` value is masked (which is expected behaviour), but the `client_secret` value is not.
```
Starting: terraform init
==============================================================================
Task         : Terraform CLI
Description  : Execute terraform cli commands
Version      : 0.7.8
Author       : Charles Zipp
Help         : 
==============================================================================
C:\Tools\terraform.exe version
Terraform v1.3.8
on windows_amd64

Your version of Terraform is out of date! The latest version
is 1.3.9. You can update by downloading from https://www.terraform.io/downloads.html
C:\Tools\terraform.exe init -backend-config=storage_account_name=<MY_STORAGE_ACCOUNT_NAME> -backend-config=container_name=<MY_BLOB_CONTAINER_NAME> -backend-config=key=<MY_STATE>.terraform.tfstate -backend-config=resource_group_name=<MY_RESOURCE_GROUP_NAME> -backend-config=subscription_id=<MY_SUBSCRIPTION_ID> -backend-config=tenant_id=<MY_TENANT_ID> -backend-config=client_id=*** -backend-config=client_secret=supersecretpassword
Initializing modules...
...
```
**Expected behavior**
`client_id` and `client_secret` values should be masked in the job log output/results screen of the ADO Agent pipeline run.

**Agent Configuration**
 - OS: Windows 2019 Server
 - Self Hosted
 - Terraform version used = 1.3.8
 - AzureCLI version used = 2.45.0

**Additional context**
There is a token replacement templates that runs immediately before the Terraform init task. The INIT initializes the backend storage in Azure Storage Account with relevant Service Principal credentials, and prepares to run Terraform plan. The INIT does succeed just fine, but I just want to know why the secret is not getting masked in some Stages of my pipeline, but in the next Stage of the pipeline it does get masked, when both Stages are referencing the same `terraform_init.yml` template file.
