### ISSUE TITLE
Terraform Plan Tab in Pipeline runs details doesn't show plans 

### ISSUE THREAD

**Issue by brampostma** [charleszipp/azure-pipelines-tasks-terraform#342]
**Describe the bug**
I have a Azure Devops Pipeline in yaml with a Terraform Plan task in every Stage (with stages dev,tst,acc,prd). Those Plan tasks publish their plans, this works fine and I can see the plans from the pipeline run overview page. The problem is that when the plan task of the first stage (dev) does not have any changes it will not publish anything to the pipeline run overview, even tho the other stages plan tasks contain have changes.

**To Reproduce**
1. Setup a pipeline with multiple stages and a terraform@cli tasks in each stage:
```  
    - task: TerraformCLI@0
    displayName: 'Terraform : plan'
    inputs:
      command: plan
      publishPlanResults: ${{ parameters.publishPlanResults }}
```
2. Execute pipeline where the first stage doesn't have any changes and further stages do.
3. Look at Terraform plan tab in pipeline run results page.

**Expected behavior**
I expect to see the plans of the other stages to be visable in the pipeline run overview, but i get this:
![image](https://user-images.githubusercontent.com/34541396/236818242-78768a5c-ed02-4acd-b30b-daa55b7a378e.png)

even tho the test stage has changes:
![image](https://user-images.githubusercontent.com/34541396/236819653-f69de39d-80f5-43ac-903e-9a79ac8b4b4e.png)
