### ISSUE TITLE
Terraform workspace select doesn't support (or reads) commandOptions

### ISSUE THREAD

**Issue by dperez112** [charleszipp/azure-pipelines-tasks-terraform#353]
**Describe the bug**
When trying to use the select workspace task commandOptions are not taken like in other commands.
**To Reproduce**
1. Setup pipeline with a task similar to:
```
    task: TerraformCLI@0
    displayName: Select Worspace
    inputs:
      command: workspace
      workspaceSubCommand: select
      commandOptions: -or-create
      workingDirectory: directory
      workspaceName: workspacename
```
3. Execute pipeline
4. Command Options are not executed

**Expected behavior**
Command options should be executed
