### ISSUE TITLE
[error] Terraform backend initialization for AzureRM only support service principal authorization

### ISSUE THREAD

**Issue by rhollins** [charleszipp/azure-pipelines-tasks-terraform#378]
**Describe the bug**

After converting Service Connection to the new one using workload identity federation with openid connect terraform cli tasks return error: [error] Terraform backend initialization for AzureRM only support service principal authorization

**To Reproduce**
1. Create SC using new Workload Identity federation (automatic)
2. Provide new SC name as backendServiceArm 

```
    - task: TerraformCLI@0
      displayName: 'terraform init'
      inputs:
        command: init
        backendType: azurerm
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
        ensureBackend: false
        backendServiceArm: ${{ parameters.backendServiceArm }}
```

**Expected behavior**
terraform init should work

**Screenshots**

**Pipeline Logs**
##[error]Terraform backend initialization for AzureRM only support service principal authorization

**Agent Configuration**
 - OS: ubuntu
 - Self Hosted
 - Terraform version used (Default for hosted agent is acceptable) 1.5.6
 - AzureCLI version used (Default for hosted agent is acceptable or N/A) 1.0.2 
 - extension version: 1.0.2 (Latest)

**Additional context**
Same step works from SC created using for example "Service principal (automatic)"
