### ISSUE TITLE
Support for -var on Terraform plan

### ISSUE THREAD

**Issue by Lars-Kolsaker** [charleszipp/azure-pipelines-tasks-terraform#399]
Any plans to support the command line option `-var` on the plan command?

Regards, Lars

**Comment by jaredfholgate** [comment]
Hi @Lars-Kolsaker. You can supply `-var` or `-var-file` in the `commandOptions` field. E.g.

```
- task: TerraformCLI@1
  displayName: 'terraform plan'
  inputs:
    command: plan
    environmentServiceName: 'My Azure Service Connection'
    commandOptions: '-var "my_variable=testing123" -var "my_other_variable=123456"'
```

Example usage here: https://github.com/Azure-Samples/azure-devops-terraform-oidc-ci-cd/blob/e1d267c3baa370516a7614f978ff0c1080868c91/pipelines/oidc.yml#L102
