### ISSUE TITLE
"A task is missing" error

### ISSUE THREAD

**Issue by richardoswald** [charleszipp/azure-pipelines-tasks-terraform#414]
**Describe the bug**
I receive a new error when using the TerraformCLI@0 task `A task is missing. The pipeline references a task called 'TerraformCLI'.

I also noticed that the task is now "unpublished" on the Marketplace page. Is this related? `This extension is now unpublished from Marketplace. You can choose to uninstall it.`

**To Reproduce**
1. Setup pipeline as (include yaml configuration or screenshots of classic ui editor)
```
            - task: TerraformCLI@0
              displayName: "Terraform Init: ${{ path }}"
              inputs:
                command: "init"
                workingDirectory: "$(System.DefaultWorkingDirectory)/${{ path }}"
                backendType: "selfConfigured"
                allowTelemetryCollection: false
```
3. Execute pipeline
4. See error `A task is missing. The pipeline references a task called 'TerraformCLI'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com.`

**Expected behavior**
TerraformCLI@0 task would be found and executed during pipeline

**Agent Configuration**
 - OS: Amazon Linux 2
 - Self Hosted
 - Terraform version 1.7.3
 - AzureCLI version used N/A

**Screenshots**
![image](https://github.com/jason-johnson/azure-pipelines-tasks-terraform/assets/20009874/7feefa62-2859-49eb-b04f-9b21accf9c74)

**Additional context**
This worked as of Feb. 9th, 2024
