### ISSUE TITLE
AWS - Does Terraform Init Task Support DynamoDB Backend for Locking with S3 State Files?

### ISSUE THREAD

**Issue by brandtaderrick** [charleszipp/azure-pipelines-tasks-terraform#429]
If you want to use DynamoDB in collaboration with S3 to handle locking and state checksum management, can you do that with the TerraformCLI@0 init task? I searched around the repo, but I didn't have any luck figuring out whether this would be supported with something like "dynamo_db_table: states.locks."

```- task: TerraformCLI@0
  displayName: 'terraform init'
  inputs:
    command: init
    workingDirectory: $(my_terraform_templates_dir)
    # set to `aws` to use aws backend
    backendType: aws
    # service connection name, required if backendType = aws
    backendServiceAws: env_test_aws
    # s3 bucket's region, optional if provided elsewhere (i.e. inside terraform template or command options)
    backendAwsRegion: us-east-1
    # s3 bucket name, optional if provided elsewhere (i.e. inside terraform template or command options)
    backendAwsBucket: s3-trfrm-dev-eus-czp
    # s3 path to state file, optional if provided elsewhere (i.e. inside terraform template or command options)
    backendAwsKey: 'my-env-infrax/dev-infrax'```

**Comment by jason-johnson** [comment]
@piizei  do you have any insights here?

**Comment by igordust** [comment]
From what I see from the source code the parameter is not managed, but you can add the relevant options using `-backend-config=key=value` in `commandOptions `
Eg:
```yaml
- task: TerraformCLI@0
  displayName: 'terraform init'
  inputs:
    command: init
    workingDirectory: $(my_terraform_templates_dir)
    backendType: aws
    backendServiceAws: env_test_aws
    backendAwsRegion: us-east-1
    backendAwsBucket: s3-trfrm-dev-eus-czp
    backendAwsKey: 'my-env-infrax/dev-infrax'
    commandOptions: '-backend-config=dynamodb_table=lock_table'
```
