### ISSUE TITLE
Rate limit 0 reached :: provider.terraform-provider-github when using TF CLI

### ISSUE THREAD

**Issue by kashan-ali-syed** [charleszipp/azure-pipelines-tasks-terraform#438]
Hi Team,

I need your help. 

I am using the TF CLI and during the TF plan, I am unable to set the github token. I have set this variable on the machine level, but the task doesn't get the token and the call the GitHub API as anonymous.

![image](https://github.com/user-attachments/assets/5f800833-0124-48c4-84ed-ce5d9440ac99)
https://registry.terraform.io/providers/integrations/github/latest/docs

Here is my part of yaml pipeline

```
      - task: TerraformCLI@2
        inputs:
          command: plan
          workingDirectory: '$(System.DefaultWorkingDirectory)/${{parameters.env}}'
          environmentServiceName: 'APP-SP-CORP-TF-${{parameters.env}}'
          providerAzureRmSubscriptionId: '$(subscription_id)'
          commandOptions: '-no-color -out=tfplan.json'
          allowTelemetryCollection: false
          publishPlanResults: '${{parameters.env}}'`
```

And when the API call anonymous, I got the rate limit issue in my pipeline. Can anyone face the similar issue and know the workaround for it.

<img width="758" alt="rate-limit-github-api" src="https://github.com/user-attachments/assets/e63ba5ae-22c3-45b1-959d-4591f619407d">

I am using the GitHub service connection and tried both Azure Pipeline GitHub OAuth / Personal Access Token in the Azure Pipeline. Also set the export variable during the pipeline but none of them solve the issue mentioned above..
