### ISSUE TITLE
[Azure DevOps]TypeError: (0 , webapi_1.getFederatedToken) is not a function

### ISSUE THREAD

**Issue by patrickmcgannon** [charleszipp/azure-pipelines-tasks-terraform#455]
**Describe the bug**
With our Azure DevOps task auto-upgrading from **`1.1.2` to `1.2.2`**, we are now seeing an issue on `terraform init` calls (although it could be more than just that, but that is the first usage of it).  

**To Reproduce**
1. Setup pipeline as (include yaml configuration or screenshots of classic ui editor)

```
      - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@1.1.2
        displayName: 'Terraform Init - ${{ dir }}'
        inputs:
          command: init
          workingDirectory: '$(Build.ArtifactStagingDirectory)/Artifacts/Terraform/${{ dir }}'
          backendType: self-configured
          commandOptions: '-backend=false'
```          

2. Execute pipeline
3. See error

```
##[error]TypeError: (0 , webapi_1.getFederatedToken) is not a function
```

**Expected behavior**
This is a regression from the working behavior in 1.1.2 for Azure.

**Screenshots**

**Pipeline Logs**
Include logs that help demonstrate the problem. Please make sure to redact any sensitive info such as secrets.

**Agent Configuration**
 - OS: Ubuntu - 22.04.5
 - Hosted
 - Terraform version used: 1.9.4
 - AzureCLI version used: 2.248.1
