### ISSUE TITLE
Modify the JSON output version in PLAN task

### ISSUE THREAD

**Issue by prasanna7401** [charleszipp/azure-pipelines-tasks-terraform#476]
**Describe the bug**
In the Terraform plan ADO task, the output JSON is in `v1.0` instead of the latest `v1.2`. Due to this, the JSON file does not include detailed information about what kind of operation (create, update, destroy, no-op) is done by the code.

**To Reproduce**
1. Setup pipeline with any terraform code
2. Add a `terraform plan` task and add an additional command argument `-out=tfplan` to get the plan output.
3. Add a `terraform show` task to convert this _tfplan_ file to JSON, using an additional command argument  `-json tfplan > tfplan.json`.
4. Use the below script to fetch the `change.actions` value,
  ```sh
  tfplan=$(cat tfplan.json)
  
  echo "$tfplan" | jq .
  
  actions=$(echo "$tfplan" | jq -r '.resource_changes[].change.actions[]' | sort -u)
  
  echo $actions
  ```
6. For troubleshooting purposes, Export this JSON file as a pipeline artifact, or use a `cat` statement to show the output.
7. A sample use case is [shown here](https://learn.microsoft.com/en-us/answers/questions/1436411/help-is-needed-with-azure-devops-pipeline) - When you use the script to parse the JSON output and fetch the `action` being done (create, update, delete, no-op), in JSON v1.0, the script cannot run due to very limited output. But, you can see more output in JSON v1.1, and the script succeeded. 
8. If you notice the output by using the terraform plan ADO task and a normal script, you will notice there is a difference in the JSON versions, and the output in v1.2 from the script is more detailed than that from v1.0 from the ADO task.

**Expected behavior**
The JSON output of the terraform plan is to be the latest `v1.2` so that, more additional information about the actions being done by the terraform plan is included in the plan output.

**Screenshots**
Not available.

**Pipeline Logs**

tfplan.json output
-  Using the Azure DevOps Terraform Task: `{"format_version":"1.0","terraform_version":"1.6.4",...`
- Running the terraform plan as a script: `{"format_version":"1.2","terraform_version":"1.6.4",...` 

**Agent Configuration**
 - OS: ubuntu-latest, windows-latest
 - Hosted/Self Hosted: Both
 - Terraform version used: v1.6.4 (latest)
 - AzureCLI version used (Default for the hosted agent is acceptable)

**Additional context**
I parse the action variable from the tfplan.json to find what action is being done by the code and set up the next pipeline stage action (request approvals if the action is _change_ or _destroy_, and ignore the next stage if the action is _no-op_). For more info, check this [reddit blog post](https://www.reddit.com/r/Terraform/comments/1hs2gp2/change_terraform_plan_output_json_format_version/).

**Comment by jason-johnson** [comment]
This is not related to this task.  If you want more detailed information, then the `plan` command needs to pass `-detailed-exitcode` as a parameter.  For example:

```
- task: TerraformCLI@1
      displayName: 'terraform plan'
      inputs:
        command: plan
        environmentServiceName: ${{ parameters.servicePrinciple }}
        runAzLogin: true
        workingDirectory: ${{ parameters.terraformPath }}
        commandOptions: '${{ parameters.commandOptions }} -out=$(System.DefaultWorkingDirectory)/terraform.tfplan -detailed-exitcode'
        publishPlanResults: 'main'
```
