### ISSUE TITLE
Support OIDC enhancement in Terraform 1.11.2

### ISSUE THREAD

**Issue by tlfzhylj** [charleszipp/azure-pipelines-tasks-terraform#479]
As seen in Terraform 1.11.2 there are some enhancements regarding OIDC token refresh: https://github.com/hashicorp/terraform/releases/tag/v1.11.2

The error is explained earlier in https://github.com/jason-johnson/azure-pipelines-tasks-terraform/issues/426

What can I do to get this working in Terraform version 1.11.2? I've tested and I still see the same error when waiting longer than 10 minutes between the plan and apply step.

**Comment by jason-johnson** [comment]
Those fields are set in your terraform configuration.  I don't think terraform CLI would need a change to support it.

**Comment by tlfzhylj** [comment]
This may not be the place to ask, but I'll try anyway... I don't understand how to fix the issue described in #426 

I've read the Azure DevOps Pipelines section here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_oidc#oidc-token

I tried these environment variables in the init task before the apply task:

```yaml
          - task: TerraformCLI@1
            displayName: "Run > terraform init"
            inputs:
              command: "init"
              backendType: "azurerm"
              backendServiceArm: "$(service_connection_name)"
              backendAzureRmResourceGroupName: $(tf_state_rg_name)
              backendAzureRmStorageAccountName: $(tf_state_sa_name)
              backendAzureRmContainerName: $(tf_state_container_name)
              backendAzureRmKey: "$(tf_environment).terraform.tfstate"
              workingDirectory: $(working_directory)
              allowTelemetryCollection: false
            env:
              ARM_USE_OIDC: true
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
              SYSTEM_OIDCREQUESTURI: $(System.OidcRequestUri)
              ARM_ADO_PIPELINE_SERVICE_CONNECTION_ID: $(service_connection_id)
```

I tried both the service connection name and the ID which I found here: 

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/9441dfd7-e78a-47cc-80b9-7174c81fae5b" />
