### ISSUE TITLE
Missing Terraform init -reconfigure implementation

### ISSUE THREAD

**Issue by AlNistor** [charleszipp/azure-pipelines-tasks-terraform#58]
**Describe the bug**
As a Terraform user coming from v. 0.14.5, I want to upgrade to the latest official release which is v. 1.0.0.
Because I am coming from a version before v. 0.15.0, I need to run the Terraform init command with the "-reconfigure" flag as specified by the [Terraform migration page](https://www.terraform.io/upgrade-guides/0-15.html) (last item on the page).
When I update my Azure DevOps pipeline to contain this command, I get the following error: 

```
Task         : Terraform CLI
Description  : Execute terraform cli commands
Version      : 0.6.8
Author       : Charles Zipp
Help         : 
==============================================================================
##[error]Error: Support for command "init -reconfigure" is not implemented
```

**To Reproduce**
1. Setup Terraform Init DevOps task
```
- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
      displayName: 'terraform init'
      inputs:
        command: init -reconfigure
        workingDirectory: '$(System.DefaultWorkingDirectory)/${{ parameters.artifact_name }}/${{ parameters.tf_folder }}'
        backendType: azurerm
        backendServiceArm: '${{ parameters.service_connection }}'
        ensureBackend: true
        backendAzureRmResourceGroupName: '$(TF_BACKEND_RG)'
        backendAzureRmResourceGroupLocation: '$(TF_BACKEND_LOCATION)'
        backendAzureRmStorageAccountName: '$(TF_BACKEND_STORAGEACCOUNT)'
        backendAzureRmContainerName: '${{ parameters.tf_container }}'
        backendAzureRmKey: '$(TF_BACKEND_KEY)'
```
2. Execute pipeline
3. See error
```
Task         : Terraform CLI
Description  : Execute terraform cli commands
Version      : 0.6.8
Author       : Charles Zipp
Help         : 
==============================================================================
##[error]Error: Support for command "init -reconfigure" is not implemented
```

**Expected behavior**
Terraform runs the init command and does the reconfiguration as the documentation mentions and task succeeds.

**Agent Configuration**
 - OS: Ubuntu-latest
 - Terraform version used v. 1.0.0
 - AzureCLI version used (Default for hosted agent is acceptable or N/A)

**Comment by stewartadam** [comment]
Does it work as expected if you change use `commandOptions` to provide `-reconfigure`, i.e.

```
- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
      displayName: 'terraform init'
      inputs:
        command: init
        commandOptions: -reconfigure
...
```
