### ISSUE TITLE
Issues in passing list(objects) variables via command option in Azure DevOps Pipelines

### ISSUE THREAD

**Issue by desreela** [charleszipp/azure-pipelines-tasks-terraform#87]
I identified that the issue is being caused by the Terraform command task in Azure Pipelines stripping the ‘double quotes’ in the command variables while passing it to the hosted Ubuntu agent. 

#Variable:
variable "replication_locations" {
  type = list(object({ location = string, failover_priority = number }))
    default = []
}

Original Scenario”
INPUT Command Variable in the Pipeline task: 
•	-var='replication_locations=[{ location = "ABC", failover_priority = 1}]'     

Actual execution in the agent console:
•	-var='replication_locations=[{ location = ABC, failover_priority = 1}]'

So I tried escaping the double quotes using different ways with somethings like these:
•	-var='replication_locations=[{ location = \"ABC\", failover_priority = 1}]'     
•	-var='replication_locations=[{ location = “\"ABC\"”, failover_priority = 1}]'     
•	-var='”replication_locations=[{ location = \“ABC\", failover_priority = 1}]”'     
With the above  changes, I could VISUALLY see (as shown in green below) the variable getting passed correctly to the command line(with double quotes). However all of them are failing  as the terraform identifies/discovers some stray characters also as part of the input, though it’s not shown in the console. 
Eg:

2019-10-05T11:03:42.6324045Z [command]/opt/hostedtoolcache/terraform/0.12.8/x64/terraform plan  -var='replication_locations_input=[{ location = "westus", failover_priority = 1}]'
2019-10-05T11:03:43.0815659Z [31m
2019-10-05T11:03:43.0816586Z [1m[31mError: [0m[0m[1mValue for undeclared variable[0m
2019-10-05T11:03:43.0817192Z [0mA variable named "'replication_locations_input" was assigned on the command
2019-10-05T11:03:43.0817378Z line, but the root module does not declare a variable of that name. To use
2019-10-05T11:03:43.0817621Z this value, add a "variable" block to the configuration.
2019-10-05T11:03:43.0818112Z [0m[0m
2019-10-05T11:03:43.0980533Z ##[error]Terraform command 'plan' failed with exit code '1'.:  Value for undeclared variable
2019-10-05T11:03:43.3250916Z ##[section]Finishing: terraform plan cosmos-acc-dbs

Tried the same process on both Windows and Ubuntu hosted agents n Az pipelines and getting the same problem. 

Any idea how we can pass this object via command line variable in the extension?

**Comment by bcastilho90** [comment]
Just came across this issue as well. In my case it's just a list of strings, but it removes the quotes and terraform doesn't understand the parameter.

**Comment by jcorioland** [comment]
We managed to use object notation in the task command option using the following syntax:

```
commandOptions: -var variable_name="{property1=\"$(PropertyA)\", propertyB=\"$(PropertyB)\"}" 
 -var other_variable=$(otherValue) 
```
Basically, you need to remove any quote/double quotes surrounding the whole commandOptions and you need to use `"` to surround the object and escape them for the properties inside the object.

Hope this helps!

**Comment by richardswinbank** [comment]
I experienced the same problem trying to pass a list of client IP addresses to Terraform for configuration of firewall rules. The list is declared in a pipeline variable e.g.:
```` yaml
variables:
  - name: ClientIpAddressList
    value: '["1.2.3.4","5.6.7.8"]'
````
Passing the variable into the task as a Terraform env var provided a workaround, i.e.:
````yaml
  - task: TerraformCLI@0
    displayName: Create Terraform plan
    inputs:
      command: plan
      workingDirectory: my-working-directory
      environmentServiceName: $(PipelineServiceConnection)
      commandOptions: >
        -out=tf.plan
    env:
      TF_VAR_client_ip_addresses: $(ClientIpAddressList)
````
